package structures;

public class StructSolDb {

	public String hinban;
	public float ratio;
	public int zokuNo;
	public String hinmei;
	public String sdsDisplayName;
	public String casNo;
	public String rouan;
	public float rouanMin;
	public String prtr;
	public float prtrMin;
	public float flashPoint;
	public float ignitionPoint;
	public float expLowerLimit;
	public float expUpperLimit;
	public float boilPoint;
	public float vaporPressure;
	public float steamSg;
	public float evaporationRate;
	public float oshaPel;
	public float acgih;
	public float niSsanEi;
	public float ld50;
	public int counter;
	public String nittokouName;
	public String nittokouEng;
	public String sdsNameEng;
	public String rouanTuuti;
	public String jap;
	public String chn;
	public String kasinhouNo;
	public String kasinhouType;
	public String prtrNo5;
	public String prtrBunrui4;
	public String prtrBunrui5;
	public String tokkasokuKubun;
	public String tokkasokuNo;
	public float tokkasokuTargetRange;
	public String kanriNoudo;
	public float displayMin;
	public String yuukisokuKubun;
	public String yuukisokuNo;
	public String dokugekiBunrui;
	public String dokugekiNo;
	public String unNo;
	public String unClass;
	public String unName;
	public String hsCode;
	public String update;
}
